// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWBBfUN_TGOXJJuCtQIzmXVarrDbksYv4',
    appId: '1:551407891437:web:43bd3260db6a40fce9ede4',
    messagingSenderId: '551407891437',
    projectId: 'arcade-9541f',
    authDomain: 'arcade-9541f.firebaseapp.com',
    storageBucket: 'arcade-9541f.firebasestorage.app',
    measurementId: 'G-V3EZ92ESHW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLF7auEIMPot2cH_1vLJPKWwF3zni3TNw',
    appId: '1:551407891437:android:20486788e33f8b5be9ede4',
    messagingSenderId: '551407891437',
    projectId: 'arcade-9541f',
    storageBucket: 'arcade-9541f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV12NkOqre_goWjB-v5WTN8nElXQwSkVQ',
    appId: '1:551407891437:ios:181d51411c364060e9ede4',
    messagingSenderId: '551407891437',
    projectId: 'arcade-9541f',
    storageBucket: 'arcade-9541f.firebasestorage.app',
    iosBundleId: 'com.example.helloWorld',
  );
}
